module.exports = {
    displayName: "lint:prettier",
    moduleFileExtensions: [
        "js",
        "jsx",
        "ts",
        "tsx",
        "css",
        "less",
        "scss",
        "graphql",
        "md",
        "markdown",
    ],
    runner: "jest-runner-prettier",
    testMatch: [
        "**/*.js",
        "**/*.jsx",
        "**/*.ts",
        "**/*.tsx",
        "**/*.css",
        "**/*.less",
        "**/*.scss",
        "**/*.graphql",
        "**/*.md",
        "**/*.markdown",
    ],
    testPathIgnorePatterns: [
        "/src/pages/_document.tsx",
        "/node_modules/",
        "/coverage/",
        "/sitemap/",
        "/dist/",
        "/src/types/schema.d.ts",
        "/.next/",
        "/out/",
        "README.md",
    ],
};
